using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Serialization;

public class DropTargets : EventSender, ICollisionReceiver, INeedReset
{
    public Renderer dropTargetRenderer;
    public PolygonCollider2D[] targetCols;      // Colliders for each individual target.
                                                // These must be attached to a CollisionForwarder
    public Transform[] targetBones;             // Bones attached to each individual target

    public AudioClip targetDownSound;
    public AudioClip targetsCompleteSound;
    public ParticleSystem upgradeParticles;
    
    public int singleDropScoreValue;
    public int fullDropScoreValue;
    public float bounceForce = 250f;            // How hard the ball should be bounced away after hitting a target
    
    private bool[] _targetDown;
    private float _upZ;                         // The positional Z value of an untriggered target. Copied from the
                                                // bone's starting position, which is assumed to be up. 
    
    private float _downZ;                       // Generated by subtracting from _upZ.
    
    private List<Material> _materials = new List<Material>();
    private AudioSource _audioSource;
    

    protected override void Awake()
    {
        base.Awake();
        _targetDown = new bool[targetCols.Length];
        _upZ = targetBones[0].localPosition.z;
        _downZ = _upZ - 0.155f;
        dropTargetRenderer.GetMaterials(_materials);
        _audioSource = GetComponent<AudioSource>();
    }
    
    private void Start()
    {        
        ResetForNewGame();
    }

    public void ResetForNewGame()
    {
        RaiseAll();
    }

    private void Drop(int index)
    {
        Vector3 pos = targetBones[index].transform.localPosition;        
        targetBones[index].transform.localPosition = new Vector3(pos.x, pos.y, _downZ);
        _materials[index + 1].SetInt("_LightOn", 1);
        _materials[index + 1].SetInt("_BlinkType", 2);
    }

    private void Raise(int index)
    {
        Vector3 pos = targetBones[index].transform.localPosition;        
        targetBones[index].transform.localPosition = new Vector3(pos.x, pos.y, _upZ);
        _materials[index + 1].SetInt("_LightOn", 1);
        _materials[index + 1].SetInt("_BlinkType", 0);
    }

    private void RaiseAll()
    {
        for (int i = 0; i < targetCols.Length; i++)
        {
            _targetDown[i] = false;
            targetCols[i].isTrigger = false;
            Raise(i);            
        }
    }
    
    public void SetLevel(int newLevel)
    {
        if (newLevel >= GM.inst.levelColors.Length)
        {
            newLevel = GM.inst.levelColors.Length - 1;
        }
        
        _materials[0].SetColor("_Color", GM.inst.levelColors[newLevel]);
        
        if (newLevel > 0)
        {
            var settings = upgradeParticles.main;
            Color newCol = GM.inst.levelColors[newLevel];
            newCol.a = 1f;
            settings.startColor = new ParticleSystem.MinMaxGradient(newCol);
            upgradeParticles.Play();
        }
    }
    
    public void ReceiveOnCollisionEnter2D(Collision2D collision)
    {
        for (int i = 0; i < targetCols.Length; i++)
        {
            if (collision.otherCollider == targetCols[i])
            {
                _targetDown[i] = true;
                targetCols[i].isTrigger = true;
                Drop(i);

                Vector2 direction = -collision.GetContact(0).normal;
                collision.gameObject.GetComponentInParent<Ball>().AddImpulseForce(direction * bounceForce);

                
                EventInfo info = new EventInfo(this, EventType.Trigger)
                {
                    Position2D = collision.otherCollider.bounds.center
                };
                boardEvent.Invoke(info);
            }
        }
        bool allDown = true;
        for (int i = 0; i < targetCols.Length; i++)
        {
            if (!_targetDown[i])
            {
                allDown = false;
                break;
            }
        }
        if (allDown)
        {
            boardEvent.Invoke(new EventInfo(this, EventType.Trigger, name));
            if (targetsCompleteSound)
            {
                _audioSource.PlayOneShot(targetsCompleteSound);
            }
            if (fullDropScoreValue > 0)
            {
                boardEvent.Invoke(new EventInfo(this, EventType.AddPoints, fullDropScoreValue));
            }
            RaiseAll();
        }
        else
        {
            if (targetDownSound)
            {
                _audioSource.PlayOneShot(targetDownSound);
            }
            if (singleDropScoreValue > 0)
            {
                boardEvent.Invoke(new EventInfo(this, EventType.AddPoints, singleDropScoreValue));
            }
        }
    }
    public void ReceiveOnCollisionExit2D(Collision2D collision)
    {

    }
    public void ReceiveOnCollisionStay2D(Collision2D collision)
    {

    }
}
